[41][UI]Dashboard
aetheryna/crit_old pull request #7
Opened 2021-06-24 08:32 UTC by AetheryNA

Be sure to add a placeholder image named "pfp" in the images folder before running 😄

Contains: 
- Navigation Bar 📑 
- Notifications tab when clicked 🔔 
- Status tab when profile picture is clicked 💬 
- Dashboard 🗂️ 

Styling! 💅

2021-06-27 15:46 UTC, bterone commented on pages/_app.js
> +import LayoutAuth from '../src/components/layouts/LayoutAuth'
Since we've already scoped the layouts to the layouts folder, I think we can just rename the file to remove the redundant naming. What do you think? 😄 
```
LayoutAuth.js # => Auth.js
```

Edit: But we can still import the file the same way, so like
```js
import LayoutAuth from '../src/components/layouts/Auth
```
Let me know what you think. 😄

2021-06-27 15:46 UTC, bterone commented on pages/_app.js
> +import LayoutAuth from '../src/components/layouts/LayoutAuth'
Also, I don't see this import being used here. This should be safe to remove. 🤔

2021-06-27 15:46 UTC, bterone commented on public/img/icons/logoff.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
There seems to be a lot of unnecessary metadata in this SVG, we can minify it with that website that you recommended a [while back](https://vecta.io/nano), let's use it. 😄

2021-06-27 15:46 UTC, bterone commented on src/components/Navigation.js
> +            src="/img/pfp.jpg"
Do we have a profile picture for this? I don't see it in the PR. 🤔 

Also, is this going to be the profile picture applied for all users when they haven't uploaded a profile picture?

2021-06-27 15:46 UTC, bterone commented on src/components/Navigation.js
> +        <p> Copyright 2021 </p>
Shall we add the copyright symbol here? `&#169;` ©️

2021-06-27 15:46 UTC, bterone commented on src/components/layouts/LayoutBase.js
> +  }
It would be helpful to put these into a helper function, that way we can write tests for these in the future 😄

2021-06-27 15:46 UTC, bterone commented on public/styles/components/_header.scss
> +      border-radius: 999px;
Can we use `50%` here instead to make the circle? 🟢 

Same with in the `&__status` line 59.

2021-06-27 15:46 UTC, bterone commented on src/components/Navigation.js
> +          <p> Online </p>
I think there was a way to get the state from this very same prop right? 🤔 
Something like `this.prop.status`, I don't really remember. Is it possible?

2021-06-27 15:46 UTC, bterone commented on public/styles/components/_header.scss
> +    padding: {
Is there a reason for the right padding with `10px` instead of 20?
![Screen Shot 2021-06-27 at 10 34 26 PM](https://user-images.githubusercontent.com/34730459/123550534-2cb51d80-d798-11eb-9c0b-89d4cababd8b.png)

How about making this into one line like this instead? 😄 
```css
padding: 20px;
```

2021-06-27 15:46 UTC, bterone commented on public/styles/components/_header.scss
> +      border-radius: 100%;
Isn't 50% `border-radius` enough for this? 🤔

2021-06-27 15:46 UTC, bterone commented on src/components/Banner.js
> +          <ul className="banner__notifications-list">
Have we thought about the blank state that would be here if the user clicks the notifications and there's none?
We should probably add that to this component too. What do you think? 🤔

2021-07-20 17:38 UTC, AetheryNA commented on pages/_app.js
> +import LayoutAuth from '../src/components/layouts/LayoutAuth'
Yup sounds great 👍

2021-07-20 17:44 UTC, AetheryNA commented on src/components/Navigation.js
> +            src="/img/pfp.jpg"
Yes, there is.

Atm the logic for replacing the profile picture isn't implemented, was planning to do that while I was working with the backend so it's easier to test. 🤷‍♂️

2021-07-20 17:47 UTC, AetheryNA commented on src/components/Navigation.js
> +        <p> Copyright 2021 </p>
Good point xD

2021-07-20 17:53 UTC, AetheryNA commented on src/components/Navigation.js
> +          <p> Online </p>
Yes it is, I'd like to work on this when we implement the backend so we can use the user information to fill those up.

2021-07-20 17:57 UTC, AetheryNA commented on src/components/Banner.js
> +          <ul className="banner__notifications-list">
Ah yes, I was hoping to work on the logic for that during the backend implementation, it'll be easier to test if it works but in general, the way we would do it is initialize a state and pass in the notifications through there and map it here. If the state is empty it would render a "There are no notifications for you" 😸

2021-07-21 15:09 UTC, bterone requested changes

2021-07-21 15:09 UTC, bterone commented on pages/_app.js
> +import LayoutBase from '../src/components/layouts/LayoutBase'
I think if we're agreeing to remove the redundant naming from [this comment](https://github.com/AetheryNA/crit/pull/7#discussion_r659108247), then we should probably do it to `LayoutBase` too 😂

2021-07-21 15:09 UTC, bterone commented on pages/login/index.js
> +import LayoutAuth from '../../src/components/layouts/LayoutAuth'
The same comment from [here](https://github.com/AetheryNA/crit/pull/7#discussion_r659108247) 😂 , actually there's a lot of files where we could change this.

2021-07-21 15:09 UTC, bterone commented on src/components/Banner.js
> +  const handleOnClick = () => {
We should also consider the case for when the user wants to dismiss the dropdown, 
like when they click anywhere outside the dropdown 😄 
Or for accessibility reasons like when they hit escape to dismiss the dropdown. Kind of why we use libraries so we don't have to recreate all that from scratch 😂

2021-07-21 15:09 UTC, bterone commented on src/components/layouts/LayoutBase.js
> +  }
I think you missed this comment 😂

2021-07-21 15:09 UTC, bterone commented on src/components/icons/Clock.js
> +export default Clock
So for these files, we should be referring to the actual SVGs in our project, we can actually do that with `SVGR` using the webpack loader to handle it for us,
We can take a look at how it's set up in [this article](https://frontend-digest.com/how-to-import-svgs-into-nextjs-8ec6100e613f) 👍 
We'd need to install the webpack variant of [SVGR](https://www.npmjs.com/package/@svgr/webpack) and customize nextjs's webpack config so that it can read the SVGs and import them as react components.

2021-07-21 15:09 UTC, bterone commented on src/components/Navigation.js
> +  ])
This is a pretty big list to keep in here, perhaps we should extract it out if to another file if we can't find a way to refactor this 🤔 
Especially as we have a lot of imports specifically for this.

2021-07-21 15:09 UTC, bterone commented on src/components/Navigation.js
> +      className: 'header__home',
Is there any reason to have specific naming for each of these navigation items? Perhaps we can the naming more generic so it's easier to style in the future. 😄

2021-07-21 15:09 UTC, bterone commented on src/components/Navigation.js
> +      items.map((objects, i) => ({...objects, isActive: i === index}))
A minor comment here, let's be more specific with `i`, we used `item` below `const menuItems = items.map((item, index) `, so let's keep the naming here too 😄

2021-07-21 15:09 UTC, bterone commented on src/components/Navigation.js
> +    <header className="header">
There are some improvements we could do to the HTML structure. Like the `header` for instance, It's not exactly the head of the page. 😂

Each tag has a semantic purpose so let's respect it 👍 

![Screen Shot 2021-07-21 at 9 57 49 PM](https://user-images.githubusercontent.com/34730459/126511359-b8e41a47-7265-4089-b520-5f777192febd.png)

2021-07-22 20:26 UTC, AetheryNA commented on src/components/Banner.js
> +  const handleOnClick = () => {
Decided to use [Tailwind UI](https://tailwindui.com/) for this. Will probably swap to this permanently when styling or building components in the future. Makes my life easier. 😅

2021-07-22 20:39 UTC, AetheryNA commented on src/components/Navigation.js
> +  ])
Made it a separate file in the helpers folder, just an array of objects and setting the state in the navigation bar to those items.
:tada:

2021-07-24 08:57 UTC, bterone commented on pages/_app.js
> +import LayoutAuth from '../src/components/layouts/Auth'
Is this supposed to be used here? I think this is safe to remove. 🤔

2021-07-24 08:57 UTC, bterone commented on pages/signup/quiz/index.js
> +import LayoutAuth from '../../src/components/layouts/LayoutAuth'
Is this importing the correct layout? We change it to just Auth, right? 🤔 
Actually, this is a sign of a bigger issue that we should address in our tests, E.g: Rendering each route and ensuring the page loads. 👍

2021-07-24 08:57 UTC, bterone commented on public/styles/components/_aside.scss
> +.aside {
Although there's no strict guideline, the [HTML spec](https://html.spec.whatwg.org/multipage/dom.html#classes) encourages us to steer away from using CSS tags as class names. 😄 
It's better to describe the nature of what this element is representing as it's easier to read, and naming isn't as restrictive in the long run such as having multiple layouts or multiple versions of a component. 👍 

Plus it'll be easier to break this CSS into separate components
```
_profile.scss
_dropdown-status.scss
_navigation-sidebar.scss
...
```

What do you think? 🤔

2021-07-24 08:57 UTC, bterone commented on public/styles/components/_header.scss
> +.header {
Same as the above comment, I think we can break these down into smaller components
```
_dropdown-notification.scss
_button-log-out.scss
...
```

⚠️ Also an important thing to note is that anything involving positioning the main elements like `header`, `aside`, `footer`, etc. could be in the `layout CSS`. Layouts are bigger picture, so anything that we might want to share with other layouts should be put in the layout CSS 😄

2021-07-24 08:57 UTC, bterone commented on src/components/Aside.js
> +const Aside = () => {
Let's break this down a bit, this file contains both the logic for `user_status` and `navigation_items`, so it's better to each file with only a single responsibility. 😄

2021-07-24 08:57 UTC, bterone commented on src/helpers/setPageTitle.js
> +export const capitalizeFirstLetter = (string) => {
I think since we're only capitalizing the first letter for the page titles, we can just call it from the `pageTitle` method directly, right? 🤔

2021-07-24 11:01 UTC, bterone commented on public/styles/components/_notifications.scss
> +.notifications {
Let's try to keep things `singular` and avoid plural. It reduces cognitive fatigue and chances of using the wrong selector 😄

2021-07-24 11:01 UTC, bterone commented on public/styles/components/_header.scss
> +.header {
If we're sticking with the header naming then let's name it `app-header` or something of that sort so we know that it's for the entire application. Same with the `aside => app-aside` 👍

2021-07-24 11:17 UTC, bterone approved these changes

2021-07-24 11:17 UTC, bterone commented on public/styles/components/_header-log-off.scss
> +  cursor: pointer;
This is a small reminder that we might not need the `cursor: pointer;` style when we change the `.log-off` tag into an actual button 😄

2021-07-24 11:22 UTC, merged